namespace :db do
	desc "Fill database with file data"
	task populate: :environment do
		Fixture.create!(
			"match_id" => "309389",
			"date" => "2013-08-04T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "1",
			"home_team" => "St Johnstone",
			"home_team_id" => "46",
			"away_team" => "Hearts",
			"away_team_id" => "50",
			"location" => "McDiarmid Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309390",
			"date" => "2013-08-03T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "1",
			"home_team" => "Aberdeen",
			"home_team_id" => "45",
			"away_team" => "Kilmarnock",
			"away_team_id" => "52",
			"location" => "Pittodrie Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309391",
			"date" => "2013-08-03T18:15:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "1",
			"home_team" => "Celtic",
			"home_team_id" => "54",
			"away_team" => "Ross County",
			"away_team_id" => "360",
			"location" => "Celtic Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309392",
			"date" => "2013-08-03T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "1",
			"home_team" => "Inverness C",
			"home_team_id" => "48",
			"away_team" => "St Mirren",
			"away_team_id" => "56",
			"location" => "Caledonian Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309393",
			"date" => "2013-08-02T20:45:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "1",
			"home_team" => "Partick",
			"home_team_id" => "561",
			"away_team" => "Dundee United",
			"away_team_id" => "51",
			"location" => "Firhill Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309394",
			"date" => "2013-08-04T14:15:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "1",
			"home_team" => "Hibernian",
			"home_team_id" => "53",
			"away_team" => "Motherwell",
			"away_team_id" => "47",
			"location" => "Easter Road",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309395",
			"date" => "2013-08-10T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "2",
			"home_team" => "Ross County",
			"home_team_id" => "360",
			"away_team" => "Partick",
			"away_team_id" => "561",
			"location" => "Victoria Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309396",
			"date" => "2013-12-18T20:45:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "2",
			"home_team" => "Celtic",
			"home_team_id" => "54",
			"away_team" => "St Mirren",
			"away_team_id" => "56",
			"location" => "Celtic Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309397",
			"date" => "2013-08-10T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "2",
			"home_team" => "Dundee United",
			"home_team_id" => "51",
			"away_team" => "Inverness C",
			"away_team_id" => "48",
			"location" => "Tannadice Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309398",
			"date" => "2013-08-11T13:05:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "2",
			"home_team" => "Hearts",
			"home_team_id" => "50",
			"away_team" => "Hibernian",
			"away_team_id" => "53",
			"location" => "Tynecastle Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309399",
			"date" => "2013-08-11T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "2",
			"home_team" => "Kilmarnock",
			"home_team_id" => "52",
			"away_team" => "St Johnstone",
			"away_team_id" => "46",
			"location" => "Rugby Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309400",
			"date" => "2013-08-11T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "2",
			"home_team" => "Motherwell",
			"home_team_id" => "47",
			"away_team" => "Aberdeen",
			"away_team_id" => "45",
			"location" => "Fir Park Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309401",
			"date" => "2013-08-17T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "3",
			"home_team" => "St Mirren",
			"home_team_id" => "56",
			"away_team" => "Kilmarnock",
			"away_team_id" => "52",
			"location" => "St. Mirren Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309402",
			"date" => "2013-08-17T13:30:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "3",
			"home_team" => "Aberdeen",
			"home_team_id" => "45",
			"away_team" => "Celtic",
			"away_team_id" => "54",
			"location" => "Pittodrie Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309403",
			"date" => "2013-08-17T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "3",
			"home_team" => "Hibernian",
			"home_team_id" => "53",
			"away_team" => "Dundee United",
			"away_team_id" => "51",
			"location" => "Easter Road",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309404",
			"date" => "2013-08-17T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "3",
			"home_team" => "Inverness C",
			"home_team_id" => "48",
			"away_team" => "Motherwell",
			"away_team_id" => "47",
			"location" => "Caledonian Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309405",
			"date" => "2013-08-16T20:45:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "3",
			"home_team" => "Partick",
			"home_team_id" => "561",
			"away_team" => "Hearts",
			"away_team_id" => "50",
			"location" => "Firhill Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309406",
			"date" => "2013-08-17T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "3",
			"home_team" => "St Johnstone",
			"home_team_id" => "46",
			"away_team" => "Ross County",
			"away_team_id" => "360",
			"location" => "McDiarmid Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309407",
			"date" => "2013-08-24T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "4",
			"home_team" => "Ross County",
			"home_team_id" => "360",
			"away_team" => "St Mirren",
			"away_team_id" => "56",
			"location" => "Victoria Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309408",
			"date" => "2013-08-24T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "4",
			"home_team" => "Celtic",
			"home_team_id" => "54",
			"away_team" => "Inverness C",
			"away_team_id" => "48",
			"location" => "Celtic Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309409",
			"date" => "2013-08-24T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "4",
			"home_team" => "Dundee United",
			"home_team_id" => "51",
			"away_team" => "St Johnstone",
			"away_team_id" => "46",
			"location" => "Tannadice Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309410",
			"date" => "2013-08-24T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "4",
			"home_team" => "Hearts",
			"home_team_id" => "50",
			"away_team" => "Aberdeen",
			"away_team_id" => "45",
			"location" => "Tynecastle Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309411",
			"date" => "2013-08-24T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "4",
			"home_team" => "Kilmarnock",
			"home_team_id" => "52",
			"away_team" => "Hibernian",
			"away_team_id" => "53",
			"location" => "Rugby Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309412",
			"date" => "2013-08-24T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "4",
			"home_team" => "Motherwell",
			"home_team_id" => "47",
			"away_team" => "Partick",
			"away_team_id" => "561",
			"location" => "Fir Park Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309413",
			"date" => "2013-08-31T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "5",
			"home_team" => "Aberdeen",
			"home_team_id" => "45",
			"away_team" => "St Johnstone",
			"away_team_id" => "46",
			"location" => "Pittodrie Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309414",
			"date" => "2013-08-31T13:45:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "5",
			"home_team" => "Dundee United",
			"home_team_id" => "51",
			"away_team" => "Celtic",
			"away_team_id" => "54",
			"location" => "Tannadice Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309415",
			"date" => "2013-08-31T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "5",
			"home_team" => "Hibernian",
			"home_team_id" => "53",
			"away_team" => "Ross County",
			"away_team_id" => "360",
			"location" => "Easter Road",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309416",
			"date" => "2013-08-31T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "5",
			"home_team" => "Inverness C",
			"home_team_id" => "48",
			"away_team" => "Hearts",
			"away_team_id" => "50",
			"location" => "Caledonian Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309417",
			"date" => "2013-08-31T18:30:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "5",
			"home_team" => "Motherwell",
			"home_team_id" => "47",
			"away_team" => "Kilmarnock",
			"away_team_id" => "52",
			"location" => "Fir Park Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309418",
			"date" => "2013-08-31T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "5",
			"home_team" => "St Mirren",
			"home_team_id" => "56",
			"away_team" => "Partick",
			"away_team_id" => "561",
			"location" => "St. Mirren Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309419",
			"date" => "2013-09-14T13:30:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "6",
			"home_team" => "Hearts",
			"home_team_id" => "50",
			"away_team" => "Celtic",
			"away_team_id" => "54",
			"location" => "Tynecastle Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309420",
			"date" => "2013-09-14T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "6",
			"home_team" => "Kilmarnock",
			"home_team_id" => "52",
			"away_team" => "Inverness C",
			"away_team_id" => "48",
			"location" => "Rugby Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309421",
			"date" => "2013-09-14T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "6",
			"home_team" => "Partick",
			"home_team_id" => "561",
			"away_team" => "Aberdeen",
			"away_team_id" => "45",
			"location" => "Firhill Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309422",
			"date" => "2013-09-15T13:45:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "6",
			"home_team" => "Ross County",
			"home_team_id" => "360",
			"away_team" => "Dundee United",
			"away_team_id" => "51",
			"location" => "Victoria Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309423",
			"date" => "2013-09-14T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "6",
			"home_team" => "St Johnstone",
			"home_team_id" => "46",
			"away_team" => "Hibernian",
			"away_team_id" => "53",
			"location" => "McDiarmid Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309424",
			"date" => "2013-09-14T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "6",
			"home_team" => "St Mirren",
			"home_team_id" => "56",
			"away_team" => "Motherwell",
			"away_team_id" => "47",
			"location" => "St. Mirren Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309425",
			"date" => "2013-09-21T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "7",
			"home_team" => "Aberdeen",
			"home_team_id" => "45",
			"away_team" => "Inverness C",
			"away_team_id" => "48",
			"location" => "Pittodrie Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309426",
			"date" => "2013-09-21T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "7",
			"home_team" => "Celtic",
			"home_team_id" => "54",
			"away_team" => "St Johnstone",
			"away_team_id" => "46",
			"location" => "Celtic Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309427",
			"date" => "2013-09-22T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "7",
			"home_team" => "Dundee United",
			"home_team_id" => "51",
			"away_team" => "Motherwell",
			"away_team_id" => "47",
			"location" => "Tannadice Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309428",
			"date" => "2013-09-21T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "7",
			"home_team" => "Partick",
			"home_team_id" => "561",
			"away_team" => "Kilmarnock",
			"away_team_id" => "52",
			"location" => "Firhill Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309429",
			"date" => "2013-09-21T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "7",
			"home_team" => "Hibernian",
			"home_team_id" => "53",
			"away_team" => "St Mirren",
			"away_team_id" => "56",
			"location" => "Easter Road",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309430",
			"date" => "2013-09-21T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "7",
			"home_team" => "Ross County",
			"home_team_id" => "360",
			"away_team" => "Hearts",
			"away_team_id" => "50",
			"location" => "Victoria Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309431",
			"date" => "2013-09-28T13:45:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "8",
			"home_team" => "Kilmarnock",
			"home_team_id" => "52",
			"away_team" => "Celtic",
			"away_team_id" => "54",
			"location" => "Rugby Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309432",
			"date" => "2013-09-28T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "8",
			"home_team" => "Motherwell",
			"home_team_id" => "47",
			"away_team" => "Ross County",
			"away_team_id" => "360",
			"location" => "Fir Park Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309433",
			"date" => "2013-09-28T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "8",
			"home_team" => "St Johnstone",
			"home_team_id" => "46",
			"away_team" => "Partick",
			"away_team_id" => "561",
			"location" => "McDiarmid Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309434",
			"date" => "2013-09-28T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "8",
			"home_team" => "Hearts",
			"home_team_id" => "50",
			"away_team" => "Dundee United",
			"away_team_id" => "51",
			"location" => "Tynecastle Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309435",
			"date" => "2013-09-30T20:45:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "8",
			"home_team" => "St Mirren",
			"home_team_id" => "56",
			"away_team" => "Aberdeen",
			"away_team_id" => "45",
			"location" => "St. Mirren Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309436",
			"date" => "2013-09-28T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "8",
			"home_team" => "Inverness C",
			"home_team_id" => "48",
			"away_team" => "Hibernian",
			"away_team_id" => "53",
			"location" => "Caledonian Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309437",
			"date" => "2013-10-07T20:45:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "9",
			"home_team" => "Partick",
			"home_team_id" => "561",
			"away_team" => "Hibernian",
			"away_team_id" => "53",
			"location" => "Firhill Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309438",
			"date" => "2013-10-05T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "9",
			"home_team" => "Ross County",
			"home_team_id" => "360",
			"away_team" => "Aberdeen",
			"away_team_id" => "45",
			"location" => "Victoria Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309439",
			"date" => "2013-10-05T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "9",
			"home_team" => "St Johnstone",
			"home_team_id" => "46",
			"away_team" => "Inverness C",
			"away_team_id" => "48",
			"location" => "McDiarmid Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309440",
			"date" => "2013-10-05T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "9",
			"home_team" => "Celtic",
			"home_team_id" => "54",
			"away_team" => "Motherwell",
			"away_team_id" => "47",
			"location" => "Celtic Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309441",
			"date" => "2013-10-05T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "9",
			"home_team" => "Dundee United",
			"home_team_id" => "51",
			"away_team" => "Kilmarnock",
			"away_team_id" => "52",
			"location" => "Tannadice Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309442",
			"date" => "2013-10-05T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "9",
			"home_team" => "Hearts",
			"home_team_id" => "50",
			"away_team" => "St Mirren",
			"away_team_id" => "56",
			"location" => "Tynecastle Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309443",
			"date" => "2013-10-19T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "10",
			"home_team" => "Kilmarnock",
			"home_team_id" => "52",
			"away_team" => "Ross County",
			"away_team_id" => "360",
			"location" => "Rugby Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309444",
			"date" => "2013-10-19T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "10",
			"home_team" => "Motherwell",
			"home_team_id" => "47",
			"away_team" => "Hearts",
			"away_team_id" => "50",
			"location" => "Fir Park Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309445",
			"date" => "2013-10-19T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "10",
			"home_team" => "St Mirren",
			"home_team_id" => "56",
			"away_team" => "St Johnstone",
			"away_team_id" => "46",
			"location" => "St. Mirren Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309446",
			"date" => "2013-10-19T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "10",
			"home_team" => "Aberdeen",
			"home_team_id" => "45",
			"away_team" => "Dundee United",
			"away_team_id" => "51",
			"location" => "Pittodrie Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309447",
			"date" => "2013-10-19T13:30:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "10",
			"home_team" => "Hibernian",
			"home_team_id" => "53",
			"away_team" => "Celtic",
			"away_team_id" => "54",
			"location" => "Easter Road",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309448",
			"date" => "2013-10-20T13:45:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "10",
			"home_team" => "Inverness C",
			"home_team_id" => "48",
			"away_team" => "Partick",
			"away_team_id" => "561",
			"location" => "Caledonian Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309449",
			"date" => "2013-10-27T13:45:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "11",
			"home_team" => "Partick",
			"home_team_id" => "561",
			"away_team" => "Celtic",
			"away_team_id" => "54",
			"location" => "Firhill Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309450",
			"date" => "2013-10-25T20:45:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "11",
			"home_team" => "Ross County",
			"home_team_id" => "360",
			"away_team" => "Inverness C",
			"away_team_id" => "48",
			"location" => "Victoria Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309451",
			"date" => "2013-10-27T17:05:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "11",
			"home_team" => "St Johnstone",
			"home_team_id" => "46",
			"away_team" => "Motherwell",
			"away_team_id" => "47",
			"location" => "McDiarmid Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309452",
			"date" => "2013-10-26T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "11",
			"home_team" => "Dundee United",
			"home_team_id" => "51",
			"away_team" => "St Mirren",
			"away_team_id" => "56",
			"location" => "Tannadice Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309453",
			"date" => "2013-10-26T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "11",
			"home_team" => "Hibernian",
			"home_team_id" => "53",
			"away_team" => "Aberdeen",
			"away_team_id" => "45",
			"location" => "Easter Road",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309454",
			"date" => "2013-10-26T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "11",
			"home_team" => "Kilmarnock",
			"home_team_id" => "52",
			"away_team" => "Hearts",
			"away_team_id" => "50",
			"location" => "Rugby Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309455",
			"date" => "2013-11-03T13:30:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "12",
			"home_team" => "Motherwell",
			"home_team_id" => "47",
			"away_team" => "Hibernian",
			"away_team_id" => "53",
			"location" => "Fir Park Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309456",
			"date" => "2013-11-02T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "12",
			"home_team" => "St Mirren",
			"home_team_id" => "56",
			"away_team" => "Ross County",
			"away_team_id" => "360",
			"location" => "St. Mirren Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309457",
			"date" => "2013-11-04T20:45:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "12",
			"home_team" => "Aberdeen",
			"home_team_id" => "45",
			"away_team" => "Partick",
			"away_team_id" => "561",
			"location" => "Pittodrie Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309458",
			"date" => "2013-11-02T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "12",
			"home_team" => "Celtic",
			"home_team_id" => "54",
			"away_team" => "Dundee United",
			"away_team_id" => "51",
			"location" => "Celtic Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309459",
			"date" => "2013-11-02T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "12",
			"home_team" => "Hearts",
			"home_team_id" => "50",
			"away_team" => "St Johnstone",
			"away_team_id" => "46",
			"location" => "Tynecastle Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309460",
			"date" => "2013-11-02T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "12",
			"home_team" => "Inverness C",
			"home_team_id" => "48",
			"away_team" => "Kilmarnock",
			"away_team_id" => "52",
			"location" => "Caledonian Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309461",
			"date" => "2013-11-09T13:45:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "13",
			"home_team" => "Ross County",
			"home_team_id" => "360",
			"away_team" => "Celtic",
			"away_team_id" => "54",
			"location" => "Victoria Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309462",
			"date" => "2013-11-09T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "13",
			"home_team" => "St Johnstone",
			"home_team_id" => "46",
			"away_team" => "Kilmarnock",
			"away_team_id" => "52",
			"location" => "McDiarmid Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309463",
			"date" => "2013-11-09T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "13",
			"home_team" => "Aberdeen",
			"home_team_id" => "45",
			"away_team" => "Hearts",
			"away_team_id" => "50",
			"location" => "Pittodrie Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309464",
			"date" => "2013-11-09T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "13",
			"home_team" => "Hibernian",
			"home_team_id" => "53",
			"away_team" => "Inverness C",
			"away_team_id" => "48",
			"location" => "Easter Road",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309465",
			"date" => "2013-11-09T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "13",
			"home_team" => "Motherwell",
			"home_team_id" => "47",
			"away_team" => "Dundee United",
			"away_team_id" => "51",
			"location" => "Fir Park Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309466",
			"date" => "2013-11-09T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "13",
			"home_team" => "Partick",
			"home_team_id" => "561",
			"away_team" => "St Mirren",
			"away_team_id" => "56",
			"location" => "Firhill Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309467",
			"date" => "2013-11-23T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "14",
			"home_team" => "Celtic",
			"home_team_id" => "54",
			"away_team" => "Aberdeen",
			"away_team_id" => "45",
			"location" => "Celtic Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309468",
			"date" => "2013-11-23T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "14",
			"home_team" => "Kilmarnock",
			"home_team_id" => "52",
			"away_team" => "Motherwell",
			"away_team_id" => "47",
			"location" => "Rugby Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309469",
			"date" => "2013-11-23T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "14",
			"home_team" => "Dundee United",
			"home_team_id" => "51",
			"away_team" => "Partick",
			"away_team_id" => "561",
			"location" => "Tannadice Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309470",
			"date" => "2013-11-23T13:45:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "14",
			"home_team" => "St Mirren",
			"home_team_id" => "56",
			"away_team" => "Hibernian",
			"away_team_id" => "53",
			"location" => "St. Mirren Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309471",
			"date" => "2013-11-23T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "14",
			"home_team" => "Hearts",
			"home_team_id" => "50",
			"away_team" => "Ross County",
			"away_team_id" => "360",
			"location" => "Tynecastle Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309472",
			"date" => "2013-11-23T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "14",
			"home_team" => "Inverness C",
			"home_team_id" => "48",
			"away_team" => "St Johnstone",
			"away_team_id" => "46",
			"location" => "Caledonian Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309473",
			"date" => "2013-12-07T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "15",
			"home_team" => "Motherwell",
			"home_team_id" => "47",
			"away_team" => "Celtic",
			"away_team_id" => "54",
			"location" => "Fir Park Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309474",
			"date" => "2013-12-07T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "15",
			"home_team" => "Ross County",
			"home_team_id" => "360",
			"away_team" => "Kilmarnock",
			"away_team_id" => "52",
			"location" => "Victoria Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309475",
			"date" => "2013-12-07T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "15",
			"home_team" => "St Johnstone",
			"home_team_id" => "46",
			"away_team" => "Aberdeen",
			"away_team_id" => "45",
			"location" => "McDiarmid Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309476",
			"date" => "2013-12-07T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "15",
			"home_team" => "St Mirren",
			"home_team_id" => "56",
			"away_team" => "Inverness C",
			"away_team_id" => "48",
			"location" => "St. Mirren Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309477",
			"date" => "2013-12-07T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "15",
			"home_team" => "Dundee United",
			"home_team_id" => "51",
			"away_team" => "Hearts",
			"away_team_id" => "50",
			"location" => "Tannadice Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309478",
			"date" => "2013-12-07T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "15",
			"home_team" => "Hibernian",
			"home_team_id" => "53",
			"away_team" => "Partick",
			"away_team_id" => "561",
			"location" => "Easter Road",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309479",
			"date" => "2013-12-14T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "16",
			"home_team" => "Kilmarnock",
			"home_team_id" => "52",
			"away_team" => "Dundee United",
			"away_team_id" => "51",
			"location" => "Rugby Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309480",
			"date" => "2013-12-14T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "16",
			"home_team" => "Partick",
			"home_team_id" => "561",
			"away_team" => "St Johnstone",
			"away_team_id" => "46",
			"location" => "Firhill Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309481",
			"date" => "2013-12-14T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "16",
			"home_team" => "Ross County",
			"home_team_id" => "360",
			"away_team" => "Motherwell",
			"away_team_id" => "47",
			"location" => "Victoria Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309482",
			"date" => "2013-12-14T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "16",
			"home_team" => "Aberdeen",
			"home_team_id" => "45",
			"away_team" => "St Mirren",
			"away_team_id" => "56",
			"location" => "Pittodrie Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309483",
			"date" => "2013-12-14T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "16",
			"home_team" => "Celtic",
			"home_team_id" => "54",
			"away_team" => "Hibernian",
			"away_team_id" => "53",
			"location" => "Celtic Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309484",
			"date" => "2013-12-14T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "16",
			"home_team" => "Hearts",
			"home_team_id" => "50",
			"away_team" => "Inverness C",
			"away_team_id" => "48",
			"location" => "Tynecastle Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309485",
			"date" => "2013-12-21T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "17",
			"home_team" => "Inverness C",
			"home_team_id" => "48",
			"away_team" => "Aberdeen",
			"away_team_id" => "45",
			"location" => "Caledonian Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309486",
			"date" => "2013-12-21T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "17",
			"home_team" => "Kilmarnock",
			"home_team_id" => "52",
			"away_team" => "Partick",
			"away_team_id" => "561",
			"location" => "Rugby Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309487",
			"date" => "2013-12-21T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "17",
			"home_team" => "Motherwell",
			"home_team_id" => "47",
			"away_team" => "St Mirren",
			"away_team_id" => "56",
			"location" => "Fir Park Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309488",
			"date" => "2013-12-21T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "17",
			"home_team" => "Celtic",
			"home_team_id" => "54",
			"away_team" => "Hearts",
			"away_team_id" => "50",
			"location" => "Celtic Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309489",
			"date" => "2013-12-21T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "17",
			"home_team" => "Dundee United",
			"home_team_id" => "51",
			"away_team" => "Ross County",
			"away_team_id" => "360",
			"location" => "Tannadice Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309490",
			"date" => "2013-12-21T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "17",
			"home_team" => "Hibernian",
			"home_team_id" => "53",
			"away_team" => "St Johnstone",
			"away_team_id" => "46",
			"location" => "Easter Road",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309491",
			"date" => "2013-12-26T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "18",
			"home_team" => "St Johnstone",
			"home_team_id" => "46",
			"away_team" => "Celtic",
			"away_team_id" => "54",
			"location" => "McDiarmid Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309492",
			"date" => "2013-12-26T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "18",
			"home_team" => "St Mirren",
			"home_team_id" => "56",
			"away_team" => "Dundee United",
			"away_team_id" => "51",
			"location" => "St. Mirren Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309493",
			"date" => "2013-12-26T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "18",
			"home_team" => "Aberdeen",
			"home_team_id" => "45",
			"away_team" => "Motherwell",
			"away_team_id" => "47",
			"location" => "Pittodrie Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309494",
			"date" => "2013-12-26T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "18",
			"home_team" => "Hearts",
			"home_team_id" => "50",
			"away_team" => "Kilmarnock",
			"away_team_id" => "52",
			"location" => "Tynecastle Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309495",
			"date" => "2013-12-26T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "18",
			"home_team" => "Partick",
			"home_team_id" => "561",
			"away_team" => "Inverness C",
			"away_team_id" => "48",
			"location" => "Firhill Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309496",
			"date" => "2013-12-26T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "18",
			"home_team" => "Ross County",
			"home_team_id" => "360",
			"away_team" => "Hibernian",
			"away_team_id" => "53",
			"location" => "Victoria Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309497",
			"date" => "2013-12-29T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "19",
			"home_team" => "St Johnstone",
			"home_team_id" => "46",
			"away_team" => "Dundee United",
			"away_team_id" => "51",
			"location" => "McDiarmid Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309498",
			"date" => "2013-12-29T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "19",
			"home_team" => "St Mirren",
			"home_team_id" => "56",
			"away_team" => "Hearts",
			"away_team_id" => "50",
			"location" => "St. Mirren Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309499",
			"date" => "2013-12-29T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "19",
			"home_team" => "Aberdeen",
			"home_team_id" => "45",
			"away_team" => "Ross County",
			"away_team_id" => "360",
			"location" => "Pittodrie Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309500",
			"date" => "2013-12-29T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "19",
			"home_team" => "Hibernian",
			"home_team_id" => "53",
			"away_team" => "Kilmarnock",
			"away_team_id" => "52",
			"location" => "Easter Road",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309501",
			"date" => "2013-12-29T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "19",
			"home_team" => "Inverness C",
			"home_team_id" => "48",
			"away_team" => "Celtic",
			"away_team_id" => "54",
			"location" => "Caledonian Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309502",
			"date" => "2013-12-29T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "19",
			"home_team" => "Partick",
			"home_team_id" => "561",
			"away_team" => "Motherwell",
			"away_team_id" => "47",
			"location" => "Firhill Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309503",
			"date" => "2014-01-01T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "20",
			"home_team" => "Motherwell",
			"home_team_id" => "47",
			"away_team" => "St Johnstone",
			"away_team_id" => "46",
			"location" => "Fir Park Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309504",
			"date" => "2014-01-01T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "20",
			"home_team" => "Kilmarnock",
			"home_team_id" => "52",
			"away_team" => "St Mirren",
			"away_team_id" => "56",
			"location" => "Rugby Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309505",
			"date" => "2014-01-01T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "20",
			"home_team" => "Celtic",
			"home_team_id" => "54",
			"away_team" => "Partick",
			"away_team_id" => "561",
			"location" => "Celtic Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309506",
			"date" => "2014-01-01T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "20",
			"home_team" => "Dundee United",
			"home_team_id" => "51",
			"away_team" => "Aberdeen",
			"away_team_id" => "45",
			"location" => "Tannadice Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309507",
			"date" => "2014-01-01T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "20",
			"home_team" => "Hibernian",
			"home_team_id" => "53",
			"away_team" => "Hearts",
			"away_team_id" => "50",
			"location" => "Easter Road",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309508",
			"date" => "2014-01-01T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "20",
			"home_team" => "Inverness C",
			"home_team_id" => "48",
			"away_team" => "Ross County",
			"away_team_id" => "360",
			"location" => "Caledonian Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309509",
			"date" => "2014-01-04T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "21",
			"home_team" => "St Mirren",
			"home_team_id" => "56",
			"away_team" => "Celtic",
			"away_team_id" => "54",
			"location" => "St. Mirren Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309510",
			"date" => "2014-01-04T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "21",
			"home_team" => "Dundee United",
			"home_team_id" => "51",
			"away_team" => "Hibernian",
			"away_team_id" => "53",
			"location" => "Tannadice Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309511",
			"date" => "2014-01-04T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "21",
			"home_team" => "Hearts",
			"home_team_id" => "50",
			"away_team" => "Partick",
			"away_team_id" => "561",
			"location" => "Tynecastle Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309512",
			"date" => "2014-01-04T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "21",
			"home_team" => "Kilmarnock",
			"home_team_id" => "52",
			"away_team" => "Aberdeen",
			"away_team_id" => "45",
			"location" => "Rugby Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309513",
			"date" => "2014-01-04T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "21",
			"home_team" => "Motherwell",
			"home_team_id" => "47",
			"away_team" => "Inverness C",
			"away_team_id" => "48",
			"location" => "Fir Park Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309514",
			"date" => "2014-01-04T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "21",
			"home_team" => "Ross County",
			"home_team_id" => "360",
			"away_team" => "St Johnstone",
			"away_team_id" => "46",
			"location" => "Victoria Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309515",
			"date" => "2014-01-11T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "22",
			"home_team" => "St Johnstone",
			"home_team_id" => "46",
			"away_team" => "St Mirren",
			"away_team_id" => "56",
			"location" => "McDiarmid Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309516",
			"date" => "2014-01-11T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "22",
			"home_team" => "Aberdeen",
			"home_team_id" => "45",
			"away_team" => "Hibernian",
			"away_team_id" => "53",
			"location" => "Pittodrie Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309517",
			"date" => "2014-01-11T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "22",
			"home_team" => "Celtic",
			"home_team_id" => "54",
			"away_team" => "Kilmarnock",
			"away_team_id" => "52",
			"location" => "Celtic Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309518",
			"date" => "2014-01-11T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "22",
			"home_team" => "Hearts",
			"home_team_id" => "50",
			"away_team" => "Motherwell",
			"away_team_id" => "47",
			"location" => "Tynecastle Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309519",
			"date" => "2014-01-11T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "22",
			"home_team" => "Inverness C",
			"home_team_id" => "48",
			"away_team" => "Dundee United",
			"away_team_id" => "51",
			"location" => "Caledonian Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309520",
			"date" => "2014-01-11T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "22",
			"home_team" => "Partick",
			"home_team_id" => "561",
			"away_team" => "Ross County",
			"away_team_id" => "360",
			"location" => "Firhill Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309521",
			"date" => "2014-01-18T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "23",
			"home_team" => "St Johnstone",
			"home_team_id" => "46",
			"away_team" => "Hearts",
			"away_team_id" => "50",
			"location" => "McDiarmid Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309522",
			"date" => "2014-01-18T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "23",
			"home_team" => "Aberdeen",
			"home_team_id" => "45",
			"away_team" => "Inverness C",
			"away_team_id" => "48",
			"location" => "Pittodrie Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309523",
			"date" => "2014-01-18T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "23",
			"home_team" => "Celtic",
			"home_team_id" => "54",
			"away_team" => "Motherwell",
			"away_team_id" => "47",
			"location" => "Celtic Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309524",
			"date" => "2014-01-18T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "23",
			"home_team" => "Hibernian",
			"home_team_id" => "53",
			"away_team" => "St Mirren",
			"away_team_id" => "56",
			"location" => "Easter Road",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309525",
			"date" => "2014-01-18T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "23",
			"home_team" => "Partick",
			"home_team_id" => "561",
			"away_team" => "Kilmarnock",
			"away_team_id" => "52",
			"location" => "Firhill Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309526",
			"date" => "2014-01-18T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "23",
			"home_team" => "Ross County",
			"home_team_id" => "360",
			"away_team" => "Dundee United",
			"away_team_id" => "51",
			"location" => "Victoria Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309527",
			"date" => "2014-01-25T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "24",
			"home_team" => "Dundee United",
			"home_team_id" => "51",
			"away_team" => "St Johnstone",
			"away_team_id" => "46",
			"location" => "Tannadice Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309528",
			"date" => "2014-01-25T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "24",
			"home_team" => "Hibernian",
			"home_team_id" => "53",
			"away_team" => "Celtic",
			"away_team_id" => "54",
			"location" => "Easter Road",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309529",
			"date" => "2014-01-25T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "24",
			"home_team" => "Kilmarnock",
			"home_team_id" => "52",
			"away_team" => "Inverness C",
			"away_team_id" => "48",
			"location" => "Rugby Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309530",
			"date" => "2014-01-25T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "24",
			"home_team" => "Motherwell",
			"home_team_id" => "47",
			"away_team" => "Aberdeen",
			"away_team_id" => "45",
			"location" => "Fir Park Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309531",
			"date" => "2014-01-25T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "24",
			"home_team" => "Ross County",
			"home_team_id" => "360",
			"away_team" => "Hearts",
			"away_team_id" => "50",
			"location" => "Victoria Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309532",
			"date" => "2014-01-25T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "24",
			"home_team" => "St Mirren",
			"home_team_id" => "56",
			"away_team" => "Partick",
			"away_team_id" => "561",
			"location" => "St. Mirren Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309533",
			"date" => "2014-02-01T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "25",
			"home_team" => "Aberdeen",
			"home_team_id" => "45",
			"away_team" => "Celtic",
			"away_team_id" => "54",
			"location" => "Pittodrie Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309534",
			"date" => "2014-02-01T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "25",
			"home_team" => "Hearts",
			"home_team_id" => "50",
			"away_team" => "St Mirren",
			"away_team_id" => "56",
			"location" => "Tynecastle Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309535",
			"date" => "2014-02-01T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "25",
			"home_team" => "Inverness C",
			"home_team_id" => "48",
			"away_team" => "Hibernian",
			"away_team_id" => "53",
			"location" => "Caledonian Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309536",
			"date" => "2014-02-01T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "25",
			"home_team" => "Kilmarnock",
			"home_team_id" => "52",
			"away_team" => "Ross County",
			"away_team_id" => "360",
			"location" => "Rugby Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309537",
			"date" => "2014-02-01T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "25",
			"home_team" => "Partick",
			"home_team_id" => "561",
			"away_team" => "Dundee United",
			"away_team_id" => "51",
			"location" => "Firhill Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309538",
			"date" => "2014-02-01T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "25",
			"home_team" => "St Johnstone",
			"home_team_id" => "46",
			"away_team" => "Motherwell",
			"away_team_id" => "47",
			"location" => "McDiarmid Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309539",
			"date" => "2014-02-15T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "26",
			"home_team" => "Celtic",
			"home_team_id" => "54",
			"away_team" => "St Johnstone",
			"away_team_id" => "46",
			"location" => "Celtic Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309540",
			"date" => "2014-02-15T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "26",
			"home_team" => "Dundee United",
			"home_team_id" => "51",
			"away_team" => "Kilmarnock",
			"away_team_id" => "52",
			"location" => "Tannadice Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309541",
			"date" => "2014-02-15T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "26",
			"home_team" => "Hibernian",
			"home_team_id" => "53",
			"away_team" => "Ross County",
			"away_team_id" => "360",
			"location" => "Easter Road",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309542",
			"date" => "2014-02-15T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "26",
			"home_team" => "Inverness C",
			"home_team_id" => "48",
			"away_team" => "Hearts",
			"away_team_id" => "50",
			"location" => "Caledonian Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309543",
			"date" => "2014-02-15T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "26",
			"home_team" => "Motherwell",
			"home_team_id" => "47",
			"away_team" => "Partick",
			"away_team_id" => "561",
			"location" => "Fir Park Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309544",
			"date" => "2014-02-15T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "26",
			"home_team" => "St Mirren",
			"home_team_id" => "56",
			"away_team" => "Aberdeen",
			"away_team_id" => "45",
			"location" => "St. Mirren Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309545",
			"date" => "2014-02-22T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "27",
			"home_team" => "Hearts",
			"home_team_id" => "50",
			"away_team" => "Celtic",
			"away_team_id" => "54",
			"location" => "Tynecastle Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309546",
			"date" => "2014-02-22T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "27",
			"home_team" => "Kilmarnock",
			"home_team_id" => "52",
			"away_team" => "Hibernian",
			"away_team_id" => "53",
			"location" => "Rugby Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309547",
			"date" => "2014-02-22T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "27",
			"home_team" => "Partick",
			"home_team_id" => "561",
			"away_team" => "Aberdeen",
			"away_team_id" => "45",
			"location" => "Firhill Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309548",
			"date" => "2014-02-22T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "27",
			"home_team" => "Ross County",
			"home_team_id" => "360",
			"away_team" => "St Mirren",
			"away_team_id" => "56",
			"location" => "Victoria Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309549",
			"date" => "2014-02-22T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "27",
			"home_team" => "St Johnstone",
			"home_team_id" => "46",
			"away_team" => "Inverness C",
			"away_team_id" => "48",
			"location" => "McDiarmid Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309550",
			"date" => "2014-02-22T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "27",
			"home_team" => "Dundee United",
			"home_team_id" => "51",
			"away_team" => "Motherwell",
			"away_team_id" => "47",
			"location" => "Tannadice Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309551",
			"date" => "2014-03-01T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "28",
			"home_team" => "Celtic",
			"home_team_id" => "54",
			"away_team" => "Inverness C",
			"away_team_id" => "48",
			"location" => "Celtic Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309552",
			"date" => "2014-03-01T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "28",
			"home_team" => "Hibernian",
			"home_team_id" => "53",
			"away_team" => "Dundee United",
			"away_team_id" => "51",
			"location" => "Easter Road",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309553",
			"date" => "2014-03-01T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "28",
			"home_team" => "Motherwell",
			"home_team_id" => "47",
			"away_team" => "Hearts",
			"away_team_id" => "50",
			"location" => "Fir Park Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309554",
			"date" => "2014-03-01T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "28",
			"home_team" => "Ross County",
			"home_team_id" => "360",
			"away_team" => "Partick",
			"away_team_id" => "561",
			"location" => "Victoria Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309555",
			"date" => "2014-03-01T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "28",
			"home_team" => "St Mirren",
			"home_team_id" => "56",
			"away_team" => "Kilmarnock",
			"away_team_id" => "52",
			"location" => "St. Mirren Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309556",
			"date" => "2014-03-01T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "28",
			"home_team" => "Aberdeen",
			"home_team_id" => "45",
			"away_team" => "St Johnstone",
			"away_team_id" => "46",
			"location" => "Pittodrie Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309557",
			"date" => "2014-03-15T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "29",
			"home_team" => "Inverness C",
			"home_team_id" => "48",
			"away_team" => "Motherwell",
			"away_team_id" => "47",
			"location" => "Caledonian Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309558",
			"date" => "2014-03-15T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "29",
			"home_team" => "Kilmarnock",
			"home_team_id" => "52",
			"away_team" => "Celtic",
			"away_team_id" => "54",
			"location" => "Rugby Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309559",
			"date" => "2014-03-15T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "29",
			"home_team" => "Partick",
			"home_team_id" => "561",
			"away_team" => "Hibernian",
			"away_team_id" => "53",
			"location" => "Firhill Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309560",
			"date" => "2014-03-15T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "29",
			"home_team" => "St Johnstone",
			"home_team_id" => "46",
			"away_team" => "Ross County",
			"away_team_id" => "360",
			"location" => "McDiarmid Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309561",
			"date" => "2014-03-15T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "29",
			"home_team" => "Dundee United",
			"home_team_id" => "51",
			"away_team" => "St Mirren",
			"away_team_id" => "56",
			"location" => "Tannadice Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309562",
			"date" => "2014-03-15T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "29",
			"home_team" => "Hearts",
			"home_team_id" => "50",
			"away_team" => "Aberdeen",
			"away_team_id" => "45",
			"location" => "Tynecastle Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309563",
			"date" => "2014-03-22T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "30",
			"home_team" => "Inverness C",
			"home_team_id" => "48",
			"away_team" => "Partick",
			"away_team_id" => "561",
			"location" => "Caledonian Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309564",
			"date" => "2014-03-22T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "30",
			"home_team" => "Motherwell",
			"home_team_id" => "47",
			"away_team" => "Ross County",
			"away_team_id" => "360",
			"location" => "Fir Park Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309565",
			"date" => "2014-03-22T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "30",
			"home_team" => "St Johnstone",
			"home_team_id" => "46",
			"away_team" => "Hibernian",
			"away_team_id" => "53",
			"location" => "McDiarmid Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309566",
			"date" => "2014-03-22T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "30",
			"home_team" => "Aberdeen",
			"home_team_id" => "45",
			"away_team" => "Kilmarnock",
			"away_team_id" => "52",
			"location" => "Pittodrie Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309567",
			"date" => "2014-03-22T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "30",
			"home_team" => "Celtic",
			"home_team_id" => "54",
			"away_team" => "St Mirren",
			"away_team_id" => "56",
			"location" => "Celtic Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309568",
			"date" => "2014-03-22T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "30",
			"home_team" => "Hearts",
			"home_team_id" => "50",
			"away_team" => "Dundee United",
			"away_team_id" => "51",
			"location" => "Tynecastle Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309569",
			"date" => "2014-03-26T20:45:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "31",
			"home_team" => "Partick",
			"home_team_id" => "561",
			"away_team" => "Celtic",
			"away_team_id" => "54",
			"location" => "Firhill Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309570",
			"date" => "2014-03-26T20:45:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "31",
			"home_team" => "Ross County",
			"home_team_id" => "360",
			"away_team" => "Aberdeen",
			"away_team_id" => "45",
			"location" => "Victoria Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309571",
			"date" => "2014-03-26T20:45:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "31",
			"home_team" => "St Mirren",
			"home_team_id" => "56",
			"away_team" => "St Johnstone",
			"away_team_id" => "46",
			"location" => "St. Mirren Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309572",
			"date" => "2014-03-26T20:45:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "31",
			"home_team" => "Dundee United",
			"home_team_id" => "51",
			"away_team" => "Inverness C",
			"away_team_id" => "48",
			"location" => "Tannadice Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309573",
			"date" => "2014-03-26T20:45:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "31",
			"home_team" => "Hibernian",
			"home_team_id" => "53",
			"away_team" => "Motherwell",
			"away_team_id" => "47",
			"location" => "Easter Road",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309574",
			"date" => "2014-03-26T20:45:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "31",
			"home_team" => "Kilmarnock",
			"home_team_id" => "52",
			"away_team" => "Hearts",
			"away_team_id" => "50",
			"location" => "Rugby Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309575",
			"date" => "2014-03-29T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "32",
			"home_team" => "Motherwell",
			"home_team_id" => "47",
			"away_team" => "Kilmarnock",
			"away_team_id" => "52",
			"location" => "Fir Park Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309576",
			"date" => "2014-03-29T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "32",
			"home_team" => "St Johnstone",
			"home_team_id" => "46",
			"away_team" => "Partick",
			"away_team_id" => "561",
			"location" => "McDiarmid Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309577",
			"date" => "2014-03-29T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "32",
			"home_team" => "Aberdeen",
			"home_team_id" => "45",
			"away_team" => "Dundee United",
			"away_team_id" => "51",
			"location" => "Pittodrie Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309578",
			"date" => "2014-03-29T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "32",
			"home_team" => "Celtic",
			"home_team_id" => "54",
			"away_team" => "Ross County",
			"away_team_id" => "360",
			"location" => "Celtic Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309579",
			"date" => "2014-03-29T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "32",
			"home_team" => "Hearts",
			"home_team_id" => "50",
			"away_team" => "Hibernian",
			"away_team_id" => "53",
			"location" => "Tynecastle Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309580",
			"date" => "2014-03-29T16:00:00+01:00",
			"league" => "Scottish Premier League",
			"round" => "32",
			"home_team" => "Inverness C",
			"home_team_id" => "48",
			"away_team" => "St Mirren",
			"away_team_id" => "56",
			"location" => "Caledonian Stadium",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309581",
			"date" => "2014-04-05T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "33",
			"home_team" => "Ross County",
			"home_team_id" => "360",
			"away_team" => "Inverness C",
			"away_team_id" => "48",
			"location" => "Victoria Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309582",
			"date" => "2014-04-05T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "33",
			"home_team" => "St Mirren",
			"home_team_id" => "56",
			"away_team" => "Motherwell",
			"away_team_id" => "47",
			"location" => "St. Mirren Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309583",
			"date" => "2014-04-05T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "33",
			"home_team" => "Dundee United",
			"home_team_id" => "51",
			"away_team" => "Celtic",
			"away_team_id" => "54",
			"location" => "Tannadice Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309584",
			"date" => "2014-04-05T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "33",
			"home_team" => "Hibernian",
			"home_team_id" => "53",
			"away_team" => "Aberdeen",
			"away_team_id" => "45",
			"location" => "Easter Road",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309585",
			"date" => "2014-04-05T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "33",
			"home_team" => "Kilmarnock",
			"home_team_id" => "52",
			"away_team" => "St Johnstone",
			"away_team_id" => "46",
			"location" => "Rugby Park",
			"report_id" => "0",
		)
		Fixture.create!(
			"match_id" => "309586",
			"date" => "2014-04-05T16:00:00+02:00",
			"league" => "Scottish Premier League",
			"round" => "33",
			"home_team" => "Partick",
			"home_team_id" => "561",
			"away_team" => "Hearts",
			"away_team_id" => "50",
			"location" => "Firhill Stadium",
			"report_id" => "0",
		)
	end
end
